### ISSUE TITLE
ContentTypeError 'Attempt to decode JSON with unexpected mimetype: text/plain'

### ISSUE THREAD

**Issue by a-essam23** [space-nuko/sd-model-manager#1]
followed the comfyui installation. running "python client.py --mode comfyui"

results in this error:

ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('http://127.0.0.1:8188/models/api/v1/loras?limit=1000')

**Comment by space-nuko** [comment]
Did the extension load correctly in ComfyUI? Check if there are any errors in which case the server won't be started (also try latest `master`)

**Comment by a-essam23** [comment]
Yes, it's working now. Thank you.
